# Generated by Django 4.2.23 on 2025-08-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1),
        ),
    ]
