# Generated by Django 4.2.23 on 2025-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0002_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game_title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
