# Generated by Django 4.2.23 on 2025-08-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0003_post_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game_title',
            field=models.CharField(default='Game Title Here', max_length=200),
        ),
    ]
