# Generated by Django 4.2.23 on 2025-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0004_alter_post_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Add Slug Here', unique=True),
        ),
    ]
