# Generated by Django 4.2.23 on 2025-08-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0006_alter_post_options_uservotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
