# Generated by Django 4.2.23 on 2025-08-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0008_alter_post_options_guide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['rating']},
        ),
    ]
