# Generated by Django 4.2.23 on 2025-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['overall_rating']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='overall_rating',
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty_rating',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='value_rating',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1),
        ),
    ]
