# Generated by Django 4.2.23 on 2025-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0010_alter_post_options_rename_rating_post_overall_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
