# Generated by Django 4.2.23 on 2025-08-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0011_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
