# Generated by Django 4.2.23 on 2025-08-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0012_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
