# Generated by Django 4.2.23 on 2025-08-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0013_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
