# Generated by Django 4.2.23 on 2025-08-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('played', '0014_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
